name: primes
version: 0.1.0.0
github: "evandertino/primes"
license: BSD3
author: "Evander Otieno"
maintainer: "evandertino@users.noreply.github.com"
copyright: "2019 Evontek Limited"

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Business Application

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/evandertino/primes#readme>

dependencies:
  - base >= 4.7 && < 5

library:
  source-dirs: src
  exposed-modules:
    - Lib.Primes
    - Lib.PrimeError

executables:
  primes-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -Wall
    dependencies:
      - primes

tests:
  primes-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - primes
      - QuickCheck
